name = "ballerina"
entrypoint = "main.bal"
extensions = [
  "bal"
]
packages = [
]
setup = [
  "wget https://dist.ballerina.io/downloads/1.2.6/ballerina-linux-installer-x64-1.2.6.deb",
  "apt-get install ./ballerina-linux-installer-x64-1.2.6.deb",
  "rm -r ballerina-linux-installer-x64-1.2.6.deb"
]


[run]
command = [
  "ballerina",
  "run",
  "./main.bal"
]

[tests]

  [tests.hello]
  code = """
import ballerina/io;
public function main() {
    io:println("Hello, World!");
}
"""
  output = "Hello, World!\n"
