name = "fortran"
entrypoint = "main.f90"
extensions = [
  "f90"
]
packages = [
  "gfortran"
]
setup = [
]
[compile]
command = [
  "gfortran",
  "-o",
  "main",
  "main.f90"
]

[run]
command = [
  "./main"
]

[tests]

  [tests.hello]
  code = "program mainprog\nprint '(\"hello\")'\nend program mainprog"
  output = "hello\n"
